Repository beyond-sw-camp/be12-fin-Catcher-GrapeField-FE, pull requests merged in 2025-04, with the labels that each got.

#31 feature/search
  src/router/index.js
  src/search/EventsResult.vue
  src/search/GeneralResult.vue
Labels: enhancement

#38 Feature/search
  src/search/EventsResult.vue
  src/search/GeneralResult.vue
  src/search/ReviewResult.vue
Labels: enhancement, design

#39 merge updates of develop
  index.html
  src/App.vue
  src/admin/List.vue
  src/admin/Request.vue
  src/admin/customercenter/CustomerCenter.vue
  src/admin/customercenter/CustomerCenterBottom.vue
  src/admin/customercenter/CustomerCenterHeader.vue
  src/admin/customercenter/Detail.vue
  src/admin/customercenter/Faq.vue
  src/admin/customercenter/Guide.vue
  src/admin/customercenter/NoticeList.vue
  src/admin/customercenter/Qna.vue
  src/admin/customercenter/RequestList.vue
  src/admin/customercenter/Search.vue
  src/assets/data/category.json
  src/assets/data/popular-chatroom.json
  src/assets/icons/empty-heart.png
  src/assets/icons/heart.png
  src/assets/icons/participant.png
  src/main/Category.vue
  src/main/Main.vue
  src/main/PopularChatRoom.vue
  src/router/index.js
  src/user/Signup.vue
  src/user/SignupSuccess.vue
Labels: enhancement

#42 Feature/header
  src/App.vue
  src/common/Header.vue
Labels: design

#76 Feature/search
  index.html
  src/assets/icons/browser_icon.svg
  src/router/index.js
  src/search/CategoryNav.vue
  src/search/EventsResult.vue
  src/search/GeneralResult.vue
  src/search/PostResult.vue
  src/search/ReviewResult.vue
Labels: design

#81 Feature/search
  src/search/EventsResult.vue
  src/search/GeneralResult.vue
Labels: design

#99 Feature/layout
  src/App.vue
  src/main/Main.vue
Labels: design

#138 [Feat] 상세페이지 게시판 페이지 디자인 변경 및 기능 추가
  src/events/EventPost.vue
Labels: enhancement

#143 [Design] 헤더 로그인/비로그인 줄바뀌지 않도록 조정
  src/common/Header.vue
Labels: design

#157 Feature/layout
  src/assets/data/banner-slides.json
  src/assets/data/events.json
  src/main/Main.vue
  src/main/PopularChatRoom.vue
  src/main/PopularPost.vue
  src/main/TopBanner.vue
Labels: enhancement, design

#174 [feat] 통합검색 결과 컴포넌트 적용
  public/data/search/events.js
  public/data/search/posts.js
  public/data/search/reviews.js
  src/events/Detail.vue
  src/search/EventsCardGeneral.vue
  src/search/EventsResult.vue
  src/search/GeneralResult.vue
  src/search/PostList.vue
  src/search/PostResult.vue
  src/search/PostRow.vue
  src/search/ReviewResult.vue
Labels: enhancement, design

#176 [design] 상세페이지 카드 간격 오류 수정
  src/events/EventShowMoreCard.vue
Labels: design

#177 [design] 고객센터 페이지 좌우 여백 추가
  src/admin/customercenter/CustomerCenter.vue
Labels: design

#178 Feature/layout
  src/assets/data/popular-post.json
  src/main/Card.vue
  src/main/Category.vue
  src/main/PopularChatRoom.vue
  src/main/PopularPost.vue
Labels: design

#195 #192 공연 전시 목록 간단 조회
  src/events/EventShowMoreList.vue
Labels: enhancement

#200 Revert "[feat] stomp-client와 SockJS 설정, Detail.vue에 연결 붙이기"
  package-lock.json
  package.json
  public/data/search/events.js
  public/data/search/posts.js
  public/data/search/reviews.js
  src/events/Detail.vue
  src/events/chat/Detail.vue
  src/events/chat/List.vue
  src/search/EventsResult.vue
  src/search/GeneralResult.vue
  src/search/PostResult.vue
  src/search/ReviewResult.vue
  src/utils/jwtHelpers.js
  src/utils/webSocketClient.js
  vite.config.js
Labels: bug

#245 Feat/chatroom/detail PiniaStore로 변경 & 스크롤기능
  src/events/chat/Detail.vue
  src/stores/useChatRoomStore.js
Labels: enhancement, design

#263 fix: 웹소켓으로 하트 누르기 로직 #262
  src/events/chat/Detail.vue
  src/stores/useChatRoomStore.js
Labels: enhancement

#261 feat/chat/jwt
  src/common/Sidebar.vue
  src/events/chat/Detail.vue
  src/stores/useChatRoomStore.js
  src/utils/webSocketClient.js
Labels: enhancement

#264 [refactor] 파라미터 token 삭제
  src/events/chat/Detail.vue
Labels: enhancement

#308 fix/header/ws 웹소켓 로직 개선 & store 함수 개선
  src/common/Header.vue
  src/common/Sidebar.vue
  src/events/chat/Detail.vue
  src/stores/useChatRoomStore.js
Labels: bug, enhancement
